### ISSUE TITLE
Norwegian characters are lost

### ISSUE THREAD

**Issue by asbjornh** [Creuna-Oslo/azure-function-job-apply#4]
When requesting the function with `{ "name": "Asbjørn" }` the resulting slack message outputs `name: Asbjrn`. It should print `name: Asbjørn` :) 

Edit: request was made using postman

**Comment by Reasonable-Solutions** [comment]
This is probably the slack api gurgling things up. No validation of any input happens here.

https://github.com/Creuna-Oslo/azure-function-job-apply/blob/master/src/Application.fs#L36

**Comment by asbjornh** [comment]
Yeah. Closing

**Comment by Reasonable-Solutions** [comment]
It's still broken tho. Surely we can fix it

**Comment by asbjornh** [comment]
Oh, ok. I got the impression that this was hard to do anything about. My bad

**Comment by asbjornh** [comment]
Closing this because I don't need to see this in my issue tracker anymore :)
If you need this issue to exist please open a new one.
